package org.devlukadev.skywarstoolsmod.utils.fetchutils;

import java.io.*;
import java.net.HttpURLConnection;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.util.concurrent.CompletableFuture;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonObject;
import com.google.gson.JsonSyntaxException;

// Util class generated by Claude
// https://claude.ai/chat/c59dd51b-77ec-4747-b686-ae8ae03405dd
public class Fetch {

    private static final int DEFAULT_TIMEOUT = 5000;
    private static final Gson GSON = new GsonBuilder().create();

    // ---------- Raw string methods ----------

    public static String get(String url) throws IOException {
        return get(url, DEFAULT_TIMEOUT);
    }

    public static String get(String url, int timeoutMs) throws IOException {
        HttpURLConnection connection = null;
        try {
            connection = (HttpURLConnection) new URL(url).openConnection();
            connection.setRequestMethod("GET");
            connection.setConnectTimeout(timeoutMs);
            connection.setReadTimeout(timeoutMs);
            connection.setRequestProperty("User-Agent", "SkyWarsToolsMod/@VER@");

            return handleResponse(connection);
        } finally {
            if (connection != null) connection.disconnect();
        }
    }

    // ---------- JSON convenience methods ----------

    public static <T> T getJson(String url, Class<T> type) throws IOException {
        return parse(get(url), type);
    }

    private static <T> T parse(String body, Class<T> type) throws IOException {
        try {
            return GSON.fromJson(body, type);
        } catch (JsonSyntaxException e) {
            throw new IOException("Failed to parse JSON response: " + e.getMessage(), e);
        }
    }

    // ---------- Async wrappers ----------

    public static CompletableFuture<String> getAsync(String url) {
        return CompletableFuture.supplyAsync(() -> {
            try {
                return get(url);
            } catch (IOException e) {
                throw new RuntimeException(e);
            }
        });
    }

    public static <T> CompletableFuture<T> getJsonAsync(String url, Class<T> type) {
        return CompletableFuture.supplyAsync(() -> {
            try {
                return getJson(url, type);
            } catch (IOException e) {
                throw new RuntimeException(e);
            }
        });
    }

    // ---------- Internal helpers ----------

    private static String handleResponse(HttpURLConnection connection) throws IOException {
        int status = connection.getResponseCode();
        InputStream stream = (status >= 200 && status < 300)
                ? connection.getInputStream()
                : connection.getErrorStream();

        String body = readStream(stream);

        if (status < 200 || status >= 300) {
            throw new IOException("HTTP " + status + ": " + body);
        }

        return body;
    }

    private static String readStream(InputStream stream) throws IOException {
        if (stream == null) return "";
        try (BufferedReader reader = new BufferedReader(
                new InputStreamReader(stream, StandardCharsets.UTF_8))) {
            StringBuilder sb = new StringBuilder();
            String line;
            while ((line = reader.readLine()) != null) {
                sb.append(line).append('\n');
            }
            return sb.toString().trim();
        }
    }
}